### ISSUE TITLE
Merge conflicts on about page

### ISSUE THREAD

**Issue by arkokoley** [aSquare14/aSquare14.github.io#2]
«««< HEAD
I'm an undergrad at IIIT Bangalore pursuing Electronics and Communication Engineering. I am interested in electronics,low frequency noise measurements and all things tech. 
I am passionate about Open Source and can often be found surfing github for cool projects. Collaborating with people and making new things makes me happy ! I am also involved in communities that promote diversity in tech .
In my free time, I read, travel and workout. I also write on Quora and Medium
=======
I'm an undergrad at IIIT Bangalore pursuing Electronics and Communication Engineering. I am passioante about electronics and all things tech. I also love Open Source and can often be found surfing github for cool projects. Collaborating with people and making new things makes me happy !
In my free time, I read, travel and workout. I write on [https://www.quora.com/profile/Atibhi-Agrawal] and [Medium](https://medium.com/@atibhi.a)
24a28fb95fd00ab6b508fbea9d5b899215572e82

**Comment by nitink4472** [comment]
What is this issue about?Can you explain me why is that story here?I would like to contribute.
